### ISSUE TITLE
Missing tag & build for 1.1.58 used by latest version 1.9.28

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android-nativesdk-prebuild#1]
The git tag android.1.9.28 declare nativeSdkVersion as 1.1.58:
https://github.com/nunchuk-io/nunchuk-android/blob/96868b4f1a64f65646134a60ca41f3ed0e9d72b6/configs/dependencies.gradle#L33

while this repo latest version is 1.1.57

**Comment by JayceLuong** [comment]
The version in the link above is 1.1.58 Could you check again?

**Comment by emanuelb** [comment]
The version that the app use is 1.1.58 and it's import nativesdk that need to be build, I am trying to avoid it by using a prebuilt version according to instructions in:
[11da98bbecfd5fd31a3340e1879601ebc736f7a7](https://github.com/nunchuk-io/nunchuk-android#alternative-solution-without-building-the-sdk-recommended)

with command
```shell
sed -i 's/io.nunchuk.android:nativesdk:${nativeSdkVersion}/com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:1.1.58@aar/g' ./nunchuk-android/configs/dependencies.gradle;
```

and it fails with error cause this repo that contain prebuilts latest version is 1.1.57  and not 1.1.58 in https://github.com/nunchuk-io/nunchuk-android-nativesdk-prebuild/releases

The error is:
```
FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':nunchuk-auth:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':nunchuk-auth:releaseCompileClasspath'.
   > Could not find com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:1.1.58.
     Required by:
         project :nunchuk-auth

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':nunchuk-core:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':nunchuk-core:releaseCompileClasspath'.
   > Could not find com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:1.1.58.
     Required by:
         project :nunchuk-core

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':nunchuk-database:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':nunchuk-database:releaseCompileClasspath'.
   > Could not find com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:1.1.58.
     Required by:
         project :nunchuk-database

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':nunchuk-domain:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':nunchuk-domain:releaseCompileClasspath'.
   > Could not find com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:1.1.58.
     Required by:
         project :nunchuk-domain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 15s
6 actionable tasks: 6 executed
```

I suggest to change the line in 
https://github.com/nunchuk-io/nunchuk-android/blob/11da98bbecfd5fd31a3340e1879601ebc736f7a7/README.md#L26
to use the `${nativeSdkVersion}` version as it's show 1.1.55 which is old version, using `${nativeSdkVersion}`  should be correct for newer versions as it's used for the dep that will be built.

to reproduce, I am trying to compile with:

```dockerfile
FROM docker.io/debian:sid-slim

RUN set -ex; \
    apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes -o APT::Install-Suggests=false --no-install-recommends \
        git \
        openjdk-11-jdk; \
    rm -rf /var/lib/apt/lists/*; \
    useradd -ms /bin/bash appuser;
     
USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/sdk" \
    ANDROID_SDK="/home/appuser/sdk" \
    ANDROID_HOME="/home/appuser/sdk"

RUN set -ex; \
    mkdir -p "/home/appuser/sdk/licenses"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/; \
    git clone --branch android.1.9.28 --depth 1 https://github.com/nunchuk-io/nunchuk-android; \
    cd nunchuk-android; \ 
    printf "\nstoreFile=nunchuk.pfx\nstorePassword=nunchuk_alias\nkeyPassword=nunchuk_alias\nkeyAlias=nunchuk_alias" > /home/appuser/nunchuk-android/keystore.properties; \
    keytool -genkey -alias nunchuk_alias -keystore /home/appuser/nunchuk-android/nunchuk-app/nunchuk.pfx -storetype PKCS12 -keyalg RSA -keysize 4096 -storepass nunchuk_alias -keypass nunchuk_alias -validity 10000 -dname CN=IL; \
    sed -i 's/io.nunchuk.android:nativesdk:${nativeSdkVersion}/com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:1.1.58@aar/g' /home/appuser/nunchuk-android/configs/dependencies.gradle;

WORKDIR /home/appuser/nunchuk-android/
```

amd then running `./gradlew assembleRelease;`

**Comment by emanuelb** [comment]
Updated latest comment, in case you saw it before the update, the TL;DR is:
1. This repo is missing git tag ang github release for version 1.1.58 used by the app, visiting below link will result in "page not found" 404
- https://github.com/nunchuk-io/nunchuk-android-nativesdk-prebuild/releases/tag/1.1.58
2. I suggest to change README.md to use the `${nativeSdkVersion}` version instead of static version  1.1.55 https://github.com/nunchuk-io/nunchuk-android/blob/11da98bbecfd5fd31a3340e1879601ebc736f7a7/README.md#L26

**Comment by JayceLuong** [comment]
Ok, I miss update prebuilt binary, will update soon, Thank you 
`I suggest to change README.md to use the ${nativeSdkVersion} version instead of static version 1.1.55` -> I think I will put a badge for latest version and update the description to 

`nativeSdk: "com.github.nunchuk-io:nunchuk-android-nativesdk-prebuild:latest@aar"`

**Comment by JayceLuong** [comment]
Updated following our discussion

**Comment by hugohn** [comment]
@emanuelb just checking, with the latest build process, were you able to reproduce the build completely?

**Comment by emanuelb** [comment]
@hugohn No, latest build for version 19.31 has FTBFS issue, that I found workaround for which likely affect RB as well details in: https://github.com/nunchuk-io/nunchuk-android/issues/19#issuecomment-1588020839 (and they might be more issues as well, RB issues in the app are reported in `nunchuk-android` repo and not in this repo, the last issue I opened and commented with diff details are: https://github.com/nunchuk-io/nunchuk-android/issues/7#issuecomment-1407557703 )
